apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-stack
  name: home-assistant
  namespace: home
spec:
  endpoints:
  - path: /api/prometheus
    port: http
  namespaceSelector:
    matchNames:
      - home
  selector:
    matchLabels:
      app.kubernetes.io/instance: home-assistant
      app.kubernetes.io/name: home-assistant
