ingress:
  enabled: true
  annotations:
    nginx.org/websocket-services: home-assistant
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  spec:
    rules:
    - host: home.simon-zengerling.de
      http:
        paths:
        - backend:
            service:
              name: home-assistant
              port:
                number: 8123
          path: /.*
          pathType: Prefix
    tls:
    - hosts:
      - home.simon-zengerling.de
      secretName: letsencrypt-prod-home-assistant