---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant-volume
  namespace: home
  labels:
    appName: home-assistant
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/home-assistant
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: 
                - jelly-node