apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
  annotations: 
    linkerd.io/inject: enabled
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: '8.3.x'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: home
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: home-assistant-values
  values: 
    replicaCount: 1