ingress:
  enabled: true
  annotations:
    nginx.org/websocket-services: home-assistant
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: home.simon-zengerling.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: letsencrypt-prod-tls-secret
      hosts:
        - home.simon-zengerling.de

prometheus:
  serviceMonitor:
    enabled: true
    additionalLabels: 
      prometheus: "true"

persistence:
  config:
    enabled: true
    storageClass: "local-storage"
    accessMode: ReadWriteOnce
    size: 1Gi