apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-source.yaml
- home-assistant-helm-release.yaml
configMapGenerator:
  - name: home-assistant-values
    files:
      - values.yaml=home-assistant-values.yaml
configurations:
  - kustomizeconfig.yaml