---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deconz-pvc
  namespace: zigbee
  labels:
    appName: deconz
spec:
  storageClassName: deconz-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M