apiVersion: v1
kind: Service
metadata:
  name: deconz-service
  namespace: zigbee
  labels:
    appName: deconz
spec:
  type: LoadBalancer
  selector:
    app: deconz
  ports:
    - port: 8124
      targetPort: 8124
